[package]
name = "ebur128"
version = "0.1.5"
authors = ["Sebastian Dr√∂ge <sebastian@centricular.com>"]
edition = "2018"
categories = ["multimedia"]
keywords = ["multimedia", "audio", "dsp"]
description = "Implementation of the EBU R128 loudness standard"
repository = "https://github.com/sdroege/ebur128"
homepage = "https://github.com/sdroege/ebur128"
license = "MIT"
readme = "README.md"

[dependencies]
bitflags = "1.0"
smallvec = "1.0"

[target.'cfg(target_arch="wasm32")'.dependencies]
wasm-bindgen = { version = "0.2", optional = true }
js-sys = { version = "0.3", optional = true }

[build-dependencies]
cc = { version = "1.0", optional = true }

[dev-dependencies]
criterion = "0.3"
float_eq = "0.5"
ebur128-c = { package = "ebur128", version = "=0.1.1" }
quickcheck = "0.9"
quickcheck_macros = "0.9"
rand = "0.7"
hound = "3"

[features]
internal-tests = []
c-tests = ["cc", "internal-tests"] # and ebur128-c, quickcheck, quickcheck_macros, rand but dev-dependencies can't be optional...
reference-tests = []
capi = []
wasm = ["wasm-bindgen", "js-sys"]

[lib]
name = "ebur128"
# Needed for wasm-bindgen...
crate-type = ["cdylib", "rlib"]

[package.metadata.capi]
min_version = "0.6.12"

[package.metadata.capi.header]
name = "ebur128.h"
subdirectory = false
generation = false

[package.metadata.capi.pkg_config]
name = "libebur128"
description = "some description"
version = "1.2.4"

[package.metadata.capi.library]
name = "ebur128"
version = "1.2.4"

[package.metadata.wasm-pack.profile.release]
# See https://github.com/rustwasm/wasm-pack/issues/886
wasm-opt = ["-Oz", "--enable-mutable-globals"]

[[bench]]
name = "interp"
harness = false
required-features = ["internal-tests"]

[[bench]]
name = "true_peak"
harness = false
required-features = ["internal-tests"]

[[bench]]
name = "history"
harness = false
required-features = ["internal-tests"]

[[bench]]
name = "filter"
harness = false
required-features = ["internal-tests"]

[[bench]]
name = "calc_gating_block"
harness = false
required-features = ["internal-tests"]

[[bench]]
name = "ebur128"
harness = false

[[test]]
name = "reference_tests"
required-features = ["reference-tests"]

[profile.dev]
opt-level = 1
